package com.uoons.india.utils

import org.lsposed.lsparanoid.Obfuscate

@Obfuscate
object AppConstants {

    const val EMPTY = ""
    const val SPACE = " "
    const val LOG_CAT = "Uoons"
    const val SUCCESS = "success"
    const val FAILURE = "failure"
    const val Uoons = "Uoons"
    const val IMAGE = "image/*"
    const val Update_PlayStore_App = "https://play.google.com/store/apps/details?id=com.uoons.india"
    const val Saas_image = "Saas_Image"
    const val LANGUAGE_ENGLISH = "en"
    const val Selected = "selected"
    const val ENGLISH = "English"
    const val GUJARATI = "Gujarti"
    const val MARATHI = "Marathi"
    const val TELUGU = "Telugu"
    const val Tamil = "Tamil"
    const val Punjabi = "Punjabi"
    const val Kannada = "Kannada"
    const val Malayalam = "Malayalam"
    const val LANGUAGE_HINDI = "hi"
    const val LANGUAGE_GUJARATI = "gu"
    const val LANGUAGE_MARATHI = "mr"
    const val LANGUAGE_TELUGU = "te"
    const val LANGUAGE_TAMIL = "ta"
    const val LANGUAGE_PUNJABI = "pa"
    const val LANGUAGE_KANNADA = "kn"
    const val LANGUAGE_MALAYALAM = "ml"
    const val HINDI = "हिंदी"
    const val CHANNEL_MODE = "ANDROID"
    const val CASH_ON_DELIVERY = "CASH ON DELIVERY"
    const val ONLINE = "ONLINE"
    const val COD = "COD"
    const val Failure = "Failure"
    const val FAILED = "FAILED"
    const val SUCCESS_ = "SUCCESS"
    const val FAILURE_ = "FAILURE"
    const val Order_Successful = "Order Successful"
    const val Order_Cancelled = "Order Cancelled"
    const val TXN_FAILURE = "TXN_FAILURE"
    const val TXN_SUCCESS = "TXN_SUCCESS"
    const val DESCRIPTION = "description"
    const val REASON = "reason"
    const val account_number = "account_number"
    const val ifsc = "ifsc"
    const val account_holder = "account_holder"
    const val bank_name = "bank_name"
    const val Success = "Success"
    const val Pending = "Pending"
    const val Dispatch = "Dispatch"
    const val Hold = "Holding"
    const val Delivered = "Delivered"
    const val Cancel = "Cancel"
    const val Refund = "Refund"
    const val Failed = "Failed"
    const val On_the_way = "On the way"
    const val Delivered_soon = "Delivered Soon"
    const val FALSE = "false"
    const val TRUE = "true"
    const val UserName = "User Name"
    const val MobileNumber = "Mobile Number"
    const val Email = "Email"
    const val Address = "Address"
    const val ErrorFetching = "Error in fetching data"
    const val dateFormateIn = "yyyy-MM-dd HH:mm:ss"
    const val dateFormateOut = "dd-MMM-yyyy hh:mm a"
    const val createImageFileDateFile = "yyyyMMdd_HHmmss"
    const val PostQuestion = "postQuestion"
    const val MyReferralCode = "myReferralCode"
    const val MyCoins = "myCoins"
    const val ReferalCode = "referalCode"
    const val IMG_ = "IMG_"
    const val zero = "0"
    const val one = "1"
    const val two = "2"
    const val three = "3"
    const val four = "4"
    const val five = "5"
    const val six = "6"
    const val seven = "7"
    const val eight = "8"
    const val nine = "9"
    const val hash = "#"
    const val PERCENTAGE = "%"
    const val Register = "register"

    const val QuestionAnser = "Questions and Answers"

    /*Animation for intent*/
    const val LEFT_TO_RIGHT = "left-to-right"
    const val RIGHT_TO_LEFT = "right-to-left"

    //----------- Notification Key Start--------------
    const val Title = "title"
    const val SORTINGLIST = "sortingList"
    const val FILTERLIST = "filterList"
    const val Body = "body"
    const val Id = "id"
    const val Image = "image"
    const val Type = "type"
    const val Name = "name"
    const val SliderProducts = "Slider Products"
    const val SorryNoProductFound = "Sorry No Products found"
    const val SorryNoMoreProduct = "Sorry No More Products"
    const val ErrorInFetchingData = "Error in fetching data"
    const val Null = "null"
    const val Choose_topic = "Choose Topics"
    const val Select_state = "Please select state"
    const val Select_occupation = "Please select occupation"
    const val Select_gender = "Please select gender"
    const val select_address_type = "Please select Address Type"

    const val HOME_ITEM_ID = "homeItemId"
    const val HOME_SUB_ITEM_ID = "homeSubItemId"
    const val PAGE = "page"
    const val SUB_CATEGORIES = "sub_categories"
    const val FILTER = "filter"
    const val SORT_BY_NAME = "sortByName"
    const val SEARCH = "search"

    const val assets_user = "https://uoons.com/assets/user/"


    const val review_id = "review_id"
    const val product_id = "product_id"
    const val question_id = "question_id"
    const val action = "action"
    const val qty = "qty"
    const val pid = "pid"
    const val PId = "pId"
    const val trackerId = "trackerId"
    const val BrandId = "14"
    const val ParentId = "parentId"
    const val SubId = "subId"
    const val CName = "cName"
    const val CId = "cId"
    const val pName = "pName"
    const val pImage = "pImage"
    const val phoneNumber = "Phone number : "
    const val ratingProduct = "ratingProduct"
    const val orderId = "orderId"
    const val product_name = "product_name"
    const val product_quantity = "product_quantity"
    const val product_image = "product_image"
    const val payAmount = "payAmount"
    const val mobileNo = "mobileNo"
    const val ORDERID = "ORDERID"
    const val orderAmount = "orderAmount"
    const val paymentMode = "paymentMode"
    const val orderMassage = "orderMassage"
    const val status = "status"
    const val SearchKey = "searchKey"
    const val No_Order_Found = "No order found"
    const val Authorization_Failed = "Authorization Failed"
    const val Auth = "Auth"
    const val Jwellary = "jwellary"
    const val SingleProduct = "101"
    const val Categories = "1"
    const val Slider = "2"
    const val PriceStore = "3"
    const val DealOfTheDay = "4"
    const val RecommendedProduct = "6"
    const val NewArrivalProducts = "11"
    const val Searching = "13"
    const val ORDER_ID = "order_id"
    const val CURRENCY = "currency"
    const val INR = "INR"
    const val AMOUNT = "amount"
    const val email = "email"
    const val CONTACT = "contact"
    const val PREFILL = "prefill"
    const val DYNAMIC_URL = "dynamicUrl"
    const val TXN_ID = "txn_id"
    const val TXN_STATUS = "txn_status"
    const val ADDRESS_ID = "addressId"
    const val COUPON = "coupon"
    const val PAYMENT_MODE = "paymentMode"
    const val SELECT_PAYMENT_MODE = "SELECT PAYMENT MODE"
    const val AUTH = "Auth"
    const val pid_ = "pid="
    const val bundle_id = "bundle_id"
    const val ECOMMERCE = "ECOMMERCE"
    const val OrderOfBundles = "Order_Of_Bundles"
    const val FetchOrder = "Fetch_Order"
    const val SHOW_PAYMENT_PAGE = "theia/api/v1/showPaymentPage"
    const val PAYTM_CALL_BACK = "theia/paytmCallback?ORDER_ID="
    const val ShareDynamicLinkProduct =
        "https://uoons.page.link?link=https://uoons.com/ShowProduct/product?pid="
    const val ShearLinkWebside = "&apn=com.uoons.india&product="
    const val NewShearLinkWebside = "&apn=com.uoons.india&product="

    const val ShareReferralLinkProduct = "https://uoons.page.link?link=https://uoons.com/referal"
    const val NewReferralWebside = "&apn=com.uoons.india"

    // const val orderMassageLink = "https://uoons.page.link?link=https://uoons.com/ShowProduct/product?pid=Auth&apn=com.intelliatech.uoons&product=Auth"
    // const val ShareDynamicLinkProduct = "https://uoons.page.link/showsingle?="
    // const val ShareDynamicLinkProduct = "https://uoons.page.link/show-product/"
    const val EcommerceApp = "Ecommerce App"
    const val TextPlain = "text/plain"
    const val ShareUsing = "Share Using"
    const val CheckLoacationAvailibilty = "Please Check Location Availability"
    const val AllReadyAddCartProduct = "The product is already added to the cart."
    const val ProductAddInCart = "Product add in your cart"
    const val Ratings = " Ratings"
    const val Total = " Total"
    const val More = " More"
    const val Less = " Less"
    //----------- Notification Key End--------------

    const val RUPEE = "₹"
    const val GALLERY_IMAGE_REQUEST = 1
    const val PAYTM_REQUEST_CODE = 3
    val CAMERA_REQUEST = 2
    var IMAGE_DIRECTORY_NAME = "Uoons"
    var PRIVACY_POLICY = "https://uoons.com/privacy-policy"
    var TERM_AND_CONDITION = "https://uoons.com/terms"

    // var PAYTM_HOST = "https://securegw-stage.paytm.in/"
    var PAYTM_HOST = "https://securegw.paytm.in/"

    // var MID = "hdYcUL28119375123051"
    var MID = "rVUATM80245920636243"
    var RAZORPAYKEY = "rzp_live_1U5ASJXM9dPCXN"


}